import 'package:flutter/material.dart';

Map<String, int> personalityMap = {
  "I’m the life of the party and love being around people.": 1,
  "I have a big heart and easily feel for others.": 2,
  "My life’s a bit of a mess—organization isn’t my strong suit.": 3,
  "I’m pretty chill and don’t stress easily.": 4,
  "Art? Meh, not really my thing.": 5,
  "I know what I want and go after it confidently.": 1,
  "I treat everyone with respect, no matter who they are.": 2,
  "Sometimes I just can’t get motivated to do stuff.": 3,
  "I bounce back quickly when life throws me curveballs.": 4,
  "I’m curious about a million different things at once.": 5,
  "I rarely feel hyped or super excited about things.": 1,
  "I tend to notice what others are doing wrong.": 2,
  "You can always count on me to come through.": 3,
  "My mood can be all over the place sometimes.": 4,
  "I’m great at finding creative ways to solve problems.": 5,
  "I tend to keep to myself and don’t talk much.": 1,
  "I don’t easily feel bad for others.": 2,
  "I like things neat, organized, and in order.": 3,
  "I can get pretty tense in certain situations.": 4,
  "I’m all about music, art, and everything creative.": 5,
  "I naturally step up and take charge in a group.": 1,
  "I sometimes start drama or pick fights with others.": 2,
  "I struggle to get going on tasks sometimes.": 3,
  "I’m confident and comfortable in my own skin.": 4,
  "I’m not really into deep, philosophical conversations.": 5,
  "I’m more laid-back and not super active.": 1,
  "I’m quick to forgive and let things go.": 2,
  "I can be a little careless at times.": 3,
  "I stay emotionally solid and don’t get upset easily.": 4,
  "Creativity isn’t really my strong suit.": 5,
  "I can be shy and introverted around people.": 1,
  "I go out of my way to help others whenever I can.": 2,
  "I like to keep my space neat and tidy.": 3,
  "I worry about stuff a lot.": 4,
  "I have a real appreciation for art, beauty, and creativity.": 5,
  "I don’t always have the power to influence people.": 1,
  "I can be rude or blunt sometimes.": 2,
  "I get things done quickly and efficiently.": 3,
  "I often feel down or sad.": 4,
  "I think deeply about things and have complex thoughts.": 5,
  "I’m always full of energy and ready to go.": 1,
  "I don’t always trust other people’s intentions.": 2,
  "I’m super reliable and always show up when needed.": 3,
  "I’m good at keeping my emotions in check.": 4,
  "My imagination doesn’t really run wild.": 5,
  "I’m talkative and love to chat with people.": 1,
  "I can come off as cold or uncaring.": 2,
  "I leave my stuff lying around and don’t clean up much.": 3,
  "I rarely feel anxious or scared.": 4,
  "Poetry and plays? Kinda boring for me.": 5,
  "I prefer when someone else takes the lead.": 1,
  "I’m polite and always try to be courteous.": 2,
  "I’ll stick with something until it’s done, no matter what.": 3,
  "I tend to feel down or blue more often than not.": 4,
  "I’m not super interested in abstract ideas.": 5,
  "I show a lot of excitement and enthusiasm for things I love.": 1,
  "I like to assume the best in people.": 2,
  "I can be a little irresponsible sometimes.": 3,
  "My emotions can change quickly and dramatically.": 4,
  "I love coming up with fresh, original ideas.": 5,
};
