// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQGyUztHKJHf4470BbCHDJn6OumFhqpEw',
    appId: '1:548669679664:web:5ebc6870860cf8ce6925f5',
    messagingSenderId: '548669679664',
    projectId: 'signintest-93754',
    authDomain: 'signintest-93754.firebaseapp.com',
    storageBucket: 'signintest-93754.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDotznd6VY35buLR_InFd16a66F0DMxs0Q',
    appId: '1:548669679664:android:c3fe1459a628a14c6925f5',
    messagingSenderId: '548669679664',
    projectId: 'signintest-93754',
    storageBucket: 'signintest-93754.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASBXlsaysa2V0z5rObps7uTtOBd8xr_WM',
    appId: '1:548669679664:ios:54763bb7cd2558b36925f5',
    messagingSenderId: '548669679664',
    projectId: 'signintest-93754',
    storageBucket: 'signintest-93754.appspot.com',
    iosBundleId: 'com.example.pt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASBXlsaysa2V0z5rObps7uTtOBd8xr_WM',
    appId: '1:548669679664:ios:54763bb7cd2558b36925f5',
    messagingSenderId: '548669679664',
    projectId: 'signintest-93754',
    storageBucket: 'signintest-93754.appspot.com',
    iosBundleId: 'com.example.pt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQGyUztHKJHf4470BbCHDJn6OumFhqpEw',
    appId: '1:548669679664:web:d278e06f6f145bee6925f5',
    messagingSenderId: '548669679664',
    projectId: 'signintest-93754',
    authDomain: 'signintest-93754.firebaseapp.com',
    storageBucket: 'signintest-93754.appspot.com',
  );
}
